### ISSUE TITLE
[Bug] HTTPError when committing files

### ISSUE THREAD

**Issue by yagueto** [calibreapp/image-actions#114] opened 2022-02-06 18:45 UTC
## Describe the bug
When it tries to commit the changes, it fails with an ```UnhandledPromiseRejectionWarning```

## How To Reproduce

1. Go to logs
2. Scroll down to 'Compress images', and then 'Committing Files...'
4. See error:
```
UnhandledPromiseRejectionWarning: HttpError: request to https://api.github.com/repos/[my username]/[my repo]/git/blobs failed, reason: read ECONNRESET
    at /usr/local/src/image-actions/node_modules/@octokit/request/lib/request.js:94:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Expected behaviour
Should add a commit to the PR :upside_down_face:  

## Screenshots
![image](https://user-images.githubusercontent.com/48566793/152696412-16ba5651-8394-4f85-8950-47274fb2ee95.png)

## Additional context
Also note that the repo is private; however, yesterday was working nicely.
When I click in the URL that it provides, it shows a 404 page

**Comment by benschwarz** [comment] 2022-02-08 00:50
Closing as a dupe of #32

**Closed by benschwarz** 2022-02-08 00:50 UTC
Labels: bug

**Comment by yagueto** [comment] 2022-02-08 10:48
> Closing as a dupe of #32

Is it related to this? In this case it doesn’t look like a rate limit, but rather an issue with an inexistent URL. Also, this is strange as I had used it before successfully, and this PR removed multiple images 😅

**Comment by benschwarz** [comment] 2022-02-16 23:01
@yagueto The URL isn't a navigable page, it's only for use in the API. The promise rejection is likely a timeout (or rate limit) due to the number of blobs being committed. I still believe it's a dupe of #32.
